Feature/rename
ONLYOFFICE/onlyoffice-plone pull request #16
Opened 2021-12-28 08:01 UTC by aleksandrfedorov97

rename documents from editor

2021-12-28 08:25 UTC, Eloncase approved these changes

2021-12-28 08:53 UTC, Eloncase approved these changes

2022-01-20 13:53 UTC, LinneyS requested changes

2022-01-20 13:53 UTC, LinneyS commented on src/onlyoffice/connector/browser/api.py
> +class Rename(BrowserView):
and make [command](https://api.onlyoffice.com/editors/command/meta) request

2022-01-25 07:25 UTC, closed without merging